version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: cowiki.nginx
    networks:
      - internal
      - default
    ports:
      - "8081:80"
    volumes:
      - ./laravel/:/var/www
      - ./nginx/.docker/default.conf:/etc/nginx/conf.d/default.conf

  vue:
    image: cowiki:staging
    # build:
    #   context: vue/.
    #   dockerfile: Dockerfile.local
    container_name: cowiki.vue
    # command: yarn run dev
    ports:
    #  - "8080:8080"
      - "8080:80"
    networks:
      - internal
    # volumes:
    #   - /app/vendor
    #   - /app/node_modules
    #   - ./vue:/app

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile.local
    container_name: cowiki.laravel
    networks:
      - internal
    ports:
      - "9000:9000"
    volumes:
      - /var/www/vendor
      - /var/www/node_modules
      - ./laravel:/var/www
      - storage:/var/www/storage/app

  database:
    image: mariadb:latest
    container_name: cowiki.db
    environment:
      - MYSQL_ROOT_PASSWORD=eworigz23nbjsdf
      - MYSQL_DATABASE=cowiki
      - MYSQL_USER=cowiki
      - MYSQL_PASSWORD=EwopEz24nbjsDF
    networks:
      - internal
    ports:
      - "8083:3306"
    volumes:
      - ./mysql/.docker/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql:ro
      - db_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$${MYSQL_PASSWORD}
      timeout: 30s
      retries: 3

networks:
  internal:
    driver: bridge

volumes:
  storage:
    external: false
  db_data:
    external: false
