<?php

namespace App\Http\Controllers;

use App\Models\State;
use App\Models\Article;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Rules\ArticleStateValidator;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\ArticleResource;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     * Avaible params:
     * – page
     * – creatorId -> filter by creator
     */
    public function index(Request $request)
    {
        $user = Auth::user();

        $articles = Article::when(!empty($request->creatorId), function ($query) use ($request) {
            $query->where('created_by_id', $request->creatorId);
        })
        ->when(empty($user), function ($query) {
            $query->published();
        })
        ->orderBy('updated_at', 'DESC')->paginate();

        return ArticleResource::collection($articles);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        if (!$user->can('add articles')) {
            return parent::abortUnauthorized();
        }

        // set draft state automatically on Article creation
        $draftState = State::where('key', 'draft')->first();
        if (!$draftState) {
            return parent::abortServerError('State not found');
        }

        $request->validate([
             'title' => 'required|max:255',
             'description' => 'required|max:1000',
             'content' => 'present|string|nullable'
         ]);

        $newArticle = Article::create([
           'title' => $request->title,
           'slug' => Str::slug($request->title),
           'description' => $request->description,
           'content' => $request->content,
           'state_id' => $draftState->id
        ]);

        return new ArticleResource($newArticle);
    }

    /**
     * Display the specified resource.
     */
    public function show(Article $article)
    {
        $user = Auth::user();
        if (!$user && $article->state->key != 'publish') {
            // @todo: this is not the default not found response as generated by the Route Model binding functionality
            abort(404);
        }

        $article->load(['attached_files', 'attached_urls', 'collections', 'comments']);

        return new ArticleResource($article);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Article $article, Request $request)
    {
        $user = Auth::user();
        if (!$user->can('edit articles')) {
            return parent::abortUnauthorized();
        }

        if($user->id !== $article->created_by_id && !$user->can('update others articles')) {
            return parent::abortUnauthorized();
        }

        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required|max:1000',
            'content' => 'present|string|nullable',
            'state.id' => ['exists:states,id', new ArticleStateValidator($article, $user)],
            'created_by.id' => 'exists:users,id'
        ]);

        $article->update([
            'title' => $request->title,
            'description' => $request->description,
            'content' => $request->content,
            'state_id' => $request->state['id']
        ]);

        // conditional update article creator
        if ($user->can('edit article creator')) {
            $article->update([
                'created_by_id' => $request->created_by['id']
            ]);
        }

        $article->load(['attached_files', 'attached_urls']);
        return new ArticleResource($article);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Article $article)
    {
        //
    }

    public function clap(Article $article)
    {
        $article->increment('claps');

        return new ArticleResource($article);
    }
}
